batch_size: 32
dataset_name: cifar10
device: auto
dirichlet_alpha: 0.5
local_epochs: 1
lr: 0.01
max_parallel_clients: 2
model_type: generic
mu: 0.01
num_clients: 2
partition_type: non-iid
rounds: 1
strategy: scaffold
