num_clients: 5
rounds: 2
local_epochs: 1
lr: 0.01
max_parallel_clients: 2
device: "cuda" # Options: "cuda", "cpu"
batch_size: 32
dataset_name: "mnist"
partition_type: "non-iid" # Options: "iid", "non-iid", "dirichlet"
dirichlet_alpha: 0.5 # Only used if partition_type is "dirichlet"
mu: 0.01 # Proximal term for FedProx
